export const ENVIROMENT_VARIABLE = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',
  MONGO_USERNAME: 'MONGO_USERNAME',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_DATABASE: 'MONGO_DATABASE',
  MONGO_HOST: 'MONGO_HOST',
};

export const STATUS = {
  FAILED: 'FAILED',
  SUCCESS: 'SUCCESS',
};
